### ISSUE TITLE
when the file viewing tree closed there's no way to get it back

### ISSUE THREAD

**Issue by bubblesofdeath** [vaibhavpandeyvpz/apkstudio#148] opened 2019-11-15 00:30 UTC
i closed the file viewing tree on the left of the screen to try and do something random and stupid and then realized there was no way to get back the tree

**Comment by vaibhavpandeyvpz** [comment] 2019-11-15 02:51
Duplicate of #142

**Closed by vaibhavpandeyvpz** 2019-11-15 02:51 UTC
